export const sampleData = [
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu Mandlesara",
        _id:"1",
        groupChat:false,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu Mandlesara",
        _id:"2",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"3",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"4",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"5",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"6",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"7",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"8",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"9",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"10",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"11",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"12",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"13",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"14",
        groupChat:true,
        members:["1","2"],
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"15",
        groupChat:true,
        members:["1","2"],
    },

]

export const sampleUsers = [
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu Mandlesara",
        _id:"1",
    },
    {
        avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
        name:"Vishnu",
        _id:"2",
    },
]

export const sampleNotification = [
    {
        sender:{
            avatar:["https://www.w3schools.com/howto/img_avatar.png"],
            name:"Vishnu Mandlesara",
        },
        _id:"1",
    },
    {
        sender:{
            avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
            name:"Vishnu",
        },
        _id:"2",
    },
]

export const sampleMessage = [
    {
        attachments:[
            {
                public_id:"vishnu",
                url:"https://www.w3schools.com/howto/img_avatar.png",
            },
        ],
        content:"vishnu ka Message Hai",
        _id:"123",
        sender:{
            _id:"user._id",
            name:"Chaman",
        },
        chat:"chatId",
        createdAt:"2024-02-12T10:41:30.6302"
    },
    {
        attachments:[
            {
                public_id:"vishnu2",
                url:"https://www.w3schools.com/howto/img_avatar.png",
            },
        ],
        content:"ha Toh",
        _id:"1234",
        sender:{
            _id:"abcde",
            name:"chapli",
        },
        chat:"chatId",
        createdAt:"2024-02-12T10:41:30.6302"
    }
]

export const dashboardData = {
    users:[
        {
            name:"Vishnu Mandlesara",
            avatar:["https://www.w3schools.com/howto/img_avatar.png"],
            _id:"1",
            username:"mandlesara_06",
            friends:20,
            groups:5,
        },
        {
            name:"Sagar Dalwala",
            avatar:["https://www.w3schools.com/howto/img_avatar.png"],
            _id:"2",
            username:"sagar_x",
            friends:10,
            groups:2,
        },
    ],
    chats:[
        {
            name:"4xLions",
            avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
            _id:"1",
            groupChat:false,
            members:[{_id:"1",avatar:"https://www.w3schools.com/howto/img_avatar.png"},{_id:"2",avatar:"https://www.w3schools.com/howto/img_avatar.png"}],
            totalMembers:2,
            totalMessages:20,
            creator:{
                name:"Vishnu Mandlesara",
                avatar:"https://www.w3schools.com/howto/img_avatar.png",
            },
        },
        {
            name:"Mama Masi",
            avatar:["https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png","https://www.w3schools.com/howto/img_avatar.png"],
            _id:"2",
            groupChat:false,
            members:[{_id:"1",avatar:"https://www.w3schools.com/howto/img_avatar.png"},{_id:"2",avatar:"https://www.w3schools.com/howto/img_avatar.png"}],
            totalMembers:4,
            totalMessages:10,
            creator:{
                name:"Sagar Dalwala",
                avatar:"https://www.w3schools.com/howto/img_avatar.png",
            },
        },
    ],
    messages:[
        {
            attachments:[],
            content:"L*uda ka Message hai",
            _id:"1",
            sender:{
                _id:"user._id",
                name:"Vishnu",
                avatar:"https://www.w3schools.com/howto/img_avatar.png",
            },
            chat:"chatId",
            groupChat:false,
            createdAt:"2024-02-12T10:41:30.6302"
        },
        {
            attachments:[
                {
                    public_id:"abc",
                    url:"https://www.w3schools.com/howto/img_avatar.png",
                }
            ],
            content:"Haa He to",
            _id:"2",
            sender:{
                _id:"cfd",
                name:"Sagar",
                avatar:"https://www.w3schools.com/howto/img_avatar.png",
            },
            chat:"chatId",
            groupChat:true,
            createdAt:"2024-02-12T10:41:30.6302"
        }
    ]
}